[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit MLX90614 Library@^2.1.5
    bblanchon/ArduinoJson@^7.4.2
    knolleary/PubSubClient@^2.8

