[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=1
lib_deps =
  adafruit/Adafruit MLX90614 Library@^2.1.5
  bblanchon/ArduinoJson@^7.3.0
  knolleary/PubSubClient@^2.8
check_tool = cppcheck
check_flags =
  cppcheck: --enable=warning,style,performance,portability
